# Generated by Django 5.0.4 on 2024-04-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Media/Student_img')),
                ('project', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('batch', models.IntegerField(null=True)),
                ('abstract', models.CharField(max_length=5000, null=True)),
                ('link', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
