# Generated by Django 5.0 on 2024-03-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0002_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
