# Generated by Django 5.0 on 2024-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0003_student_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='abstract',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
