# Generated by Django 5.0 on 2024-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0004_student_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Documentaion',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
