# Generated by Django 5.0 on 2024-03-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0006_remove_student_documentaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
