# Generated by Django 5.0 on 2024-03-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0008_remove_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
